### ISSUE TITLE
A Problem?

### ISSUE THREAD

**Issue by Pro845627** [ServerMod/SCPDiscord#162]
C:\Users\Administrator\Desktop\jiqiren\Bot>node SCPDiscordBot.js
C:\Users\Administrator\Desktop\jiqiren\Bot\SCPDiscordBot.js:5
const { token, prefix, listeningPort, statusChannels, commandChannels, verbose, cooldown, permissions, serverID, roleSync } = YAML.parse(file);
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

C:\Users\Administrator\Desktop\jiqiren\Bot>PAUSE

**Comment by Pro845627** [comment]
Version:1.1.0
This is my `config.yml`
# The bot token from https://discordapp.com/developers/
token: "NwaJaTvt_ouaM7fmMmf_ndCBuxwDkz.D11yIw.CwaJaTvt_ouaM7fmMmf_ndCBuxw"

# Prefix for discord commands
prefix: "+"

# Port to listen on, this has to be the same as the "bot port" in the plugin config and all bots you run have to have different ports or they will clash.
listeningPort: 7781

# Channel to post the bot status messages in
statusChannels: [ "551710358000369687", "551742233301221387" ]

# The channels where bot commands can be used
commandChannels: [ "551710226496094240", "551742233301221387" ]

# Log more messages to the console, useful for debugging
verbose: false

# Message cooldown, number of milliseconds to wait between sending messages. Use this if your server sends too many messages for the bot to keep up. (Bot will get delayed if it hits more than 5 messages per 5 seconds)
cooldown: 1000

# Set permissions for discord roles here, the list names are the names of the discord roles and the list items are the first word of a command. Discord admins have access to all commands.
permissions:
    "@everyone": # An everyone role example
        - list
    "Lv3": # A donator role example
        - ban
        - unban
        - kick
        - kickall
        - roundrestart
        - hidetag
        - showtag
        - list
    "Owner": # A moderator example
        - syncrole
        - ban
        - unban
        - kick
        - kickall
        - roundrestart
        - hidetag
        - showtag
        - vs_reload
        - vs_enable
        - vs_disable
        - scpd_reload
        - scpd_unsync
        - list
    "Technology": # A moderator example
        - syncrole
        - ban
        - unban
        - kick
        - kickall
        - roundrestart
        - hidetag
        - showtag
        - vs_reload
        - vs_enable
        - vs_disable
        - scpd_reload
        - scpd_unsync
        - list

# You need to enter your server id here to use role syncing, this will also show your server's roleIDs on startup
serverID: "551710045243703299"

# Dictionary of discord roles to be synced to the game, value on the left is the discord role id and the right is the name of the game role they should be granted. (Not the role title but the role designation in the RA config)
# The bot will give players the first role in the list that they have access to so make sure to put the highest ranks in the top of the list.
roleSync: 
    "Owner": "owner"
    "Technology": "tech"
    "Lv3": "admin"

**Comment by Pro845627** [comment]
#Version: 1.1.0

**Comment by Pro845627** [comment]
I think it's my 'node's problem?

**Comment by Pro845627** [comment]
I think it's my 'node's problem?

**Comment by Pro845627** [comment]
Ok,im sure that the node's version too new,i have already installed it to the older version and it's working now
