### ISSUE TITLE
Error from bot that crashes it, having to restart it after

### ISSUE THREAD

**Issue by NoManaSendHelp** [ServerMod/SCPDiscord#34]
`(node:10556) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at item.request.gen.end (/home/nomana/scp1/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/nomana/scp1/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:10556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Plugin connection lost.
events.js:188
      throw err;
      ^
 
Error: Unhandled "error" event. ([object Object])
    at Client.emit (events.js:186:19)
    at WebSocketConnection.onError (/home/nomana/scp1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/nomana/scp1/node_modules/ws/lib/event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at _receiver.cleanup (/home/nomana/scp1/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/home/nomana/scp1/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/home/nomana/scp1/node_modules/ws/lib/websocket.js:206:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)`

I currently have the bot running a separate server from the SCP servers and it works great but after some runtime it crashes and gives this error, then I have to go in and restart the bot. I currently have it setup for 1 Discord bot to send to 5 server channels for the 5 servers we run through different listening ports.

**Comment by KarlOfDuty** [comment]
I see, I will look into this. In the meantime I recommend you use pm2 to run your bots, it keeps them alive and allows you to easily start/stop them via a quick command.

**Comment by KarlOfDuty** [comment]
Done. #36
